services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      GUAC_DB_NAME: ${GUAC_DB_NAME}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./startup:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  control_dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: CONTROL_DEV
    ports:
      - "8082:8081"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:host-gateway"
    environment:
      - CORES=${CORES}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - GUAC_DB_USER=${GUAC_DB_USER}
      - GUAC_DB_PASSWORD=${GUAC_DB_PASSWORD}
      - GUAC_DB_HOST=${GUAC_DB_HOST}
      - GUAC_DB_NAME=${GUAC_DB_NAME}
    depends_on:
      - mysql
      - redis


volumes:
  mysql_data:
