name: Development Container - Build and Deploy Docker Image

on:
  workflow_dispatch: {}
  push:
    branches:
      - Dev

jobs:
  build-and-deploy:
    runs-on: self-hosted  # 로컬 Ubuntu의 actions 계정에서 실행됨

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and tag Docker image
      run: |
        docker build --no-cache -t ${{ secrets.DOCKER_HUB_USERNAME }}/control_dev:latest .
        docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/control_dev:latest ${{ secrets.DOCKER_HUB_USERNAME }}/control_dev:latest

    - name: Deploy container locally
      run: |
        IMAGE=${{ secrets.DOCKER_HUB_USERNAME }}/control_dev:latest
        docker stop CONTROL_DEV || true
        docker rm CONTROL_DEV || true
        docker run -d --name CONTROL_DEV -p 8082:8081 --restart=always \
          --add-host host.docker.internal:host-gateway \
          -e CORES="${{ secrets.CORES }}" \
          -e DB_USER="${{ secrets.DB_USER }}" \
          -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
          -e DB_HOST="${{ secrets.DB_HOST }}" \
          -e DB_NAME="${{ secrets.DB_NAME }}" \
          -e GUAC_DB_USER="${{ secrets.GUAC_DB_USER }}" \
          -e GUAC_DB_PASSWORD="${{ secrets.GUAC_DB_PASSWORD }}" \
          -e GUAC_DB_HOST="${{ secrets.GUAC_DB_HOST }}" \
          -e GUAC_DB_NAME="${{ secrets.GUAC_DB_NAME }}" \
          -e REDIS_HOST="${{ secrets.REDIS_HOST }}" \
          $IMAGE
        docker system prune -af
