name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted  # 로컬 Ubuntu의 actions 계정에서 실행됨

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and tag Docker image
      run: |
        docker build --no-cache -t ${{ secrets.DOCKER_HUB_USERNAME }}/kws_control:latest .
        docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/kws_control:latest ${{ secrets.DOCKER_HUB_USERNAME }}/kws_control:latest

    - name: Deploy container locally
      run: |
        IMAGE=${{ secrets.DOCKER_HUB_USERNAME }}/kws_control:latest
        docker stop KWS_CONTROL || true
        docker rm KWS_CONTROL || true
        docker run -d --name KWS_CONTROL -p 25119:8080 $IMAGE
        docker system prune -af
